=== elPytel/Molekuly/cards/cards.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified"
  attributeFormDefault="unqualified">

  <xs:simpleType name="ValenceInt">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1" />
      <xs:maxInclusive value="8" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="HexColor">
    <xs:restriction base="xs:string">
      <xs:pattern value="#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="CountInt">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0" />
      <xs:maxInclusive value="50" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="CardId">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z0-9_]+" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="AtomType">
    <xs:sequence>
      <xs:element name="symbol" type="xs:string" />
      <xs:element name="name" type="xs:string" />
      <xs:element name="weight" type="xs:integer" />
      <xs:element name="color" type="HexColor" />
      <xs:element name="textColor" type="HexColor" />
      <xs:element name="valence_electrons" type="ValenceInt" />
    </xs:sequence>
    <xs:attribute name="id" type="CardId" use="required" />
    <xs:attribute name="count" type="CountInt" use="optional" default="1" />
  </xs:complexType>

  <xs:complexType name="MoleculeType">
    <xs:sequence>
      <xs:element name="title" type="xs:string" />
      <xs:element name="formula" type="xs:string" />
      <xs:element name="smiles" type="xs:string" />
      <xs:element name="points" type="xs:integer" />
      <xs:element name="image" type="xs:string" />
      <xs:element name="lore" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="id" type="CardId" use="required" />
    <xs:attribute name="count" type="CountInt" use="optional" default="1" />
  </xs:complexType>

  <xs:element name="cards">
    <xs:complexType>
      <xs:sequence>
        
        <xs:element name="atoms" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="atom" type="AtomType" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="molecules" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="molecule" type="MoleculeType" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
      <xs:attribute name="game" type="xs:string" use="optional" />
      <xs:attribute name="version" type="xs:string" use="optional" />
    </xs:complexType>
  </xs:element>

</xs:schema>

=== elPytel/Molekuly/cards/metallurgy/atoms.xml
<?xml version="1.0" encoding="UTF-8"?>
<cards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../cards.xsd" game="Molekuly" version="1.0">
    
    <atoms>
        <atom id="atom_Fe" count="6">
            <symbol>Fe</symbol>
            <name>Železo</name>
            <weight>56</weight>
            <color>#D4D7D9</color>
            <textColor>#000000</textColor>
            <valence_electrons>2</valence_electrons>
        </atom>
        <atom id="atom_Al" count="4">
            <symbol>Al</symbol>
            <name>Hliník</name>
            <weight>27</weight>
            <color>#A9ACB0</color>
            <textColor>#000000</textColor>
            <valence_electrons>3</valence_electrons>
        </atom>

        <atom id="atom_Ca" count="6">
            <symbol>Ca</symbol>
            <name>Vápník</name>
            <weight>40</weight>
            <color>#FFD700</color>
            <textColor>#000000</textColor>
            <valence_electrons>2</valence_electrons>
        </atom>
        <atom id="atom_Cu" count="4">
            <symbol>Cu</symbol>
            <name>Měď</name>
            <weight>64</weight>
            <color>#D2691E</color>
            <textColor>#FFFFFF</textColor>
            <valence_electrons>2</valence_electrons>
        </atom>

        <atom id="atom_Ag" count="4">
            <symbol>Ag</symbol>
            <name>Stříbro</name>
            <weight>108</weight>
            <color>#E6E6E6</color>
            <textColor>#000000</textColor>
            <valence_electrons>1</valence_electrons>
        </atom>
        
        <atom id="atom_Au" count="2">
            <symbol>Au</symbol>
            <name>Zlato</name>
            <weight>197</weight>
            <color>#FFD700</color>
            <textColor>#000000</textColor>
            <valence_electrons>1</valence_electrons>
        </atom>
    </atoms>
</cards>

=== elPytel/Molekuly/cards/cosmetics/atoms.xml
<?xml version="1.0" encoding="UTF-8"?>
<cards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../cards.xsd" game="Molekuly" version="1.0">
    
    <atoms>
        <atom id="atom_F" count="4">
            <symbol>F</symbol>
            <name>Fluor</name>
            <weight>19</weight>
            <color>#90EE90</color>
            <textColor>#000000</textColor>
            <valence_electrons>7</valence_electrons>
        </atom>
        <atom id="atom_Si" count="4">
            <symbol>Si</symbol>
            <name>Křemík</name>
            <weight>28</weight>
            <color>#708090</color>
            <textColor>#FFFFFF</textColor>
            <valence_electrons>4</valence_electrons>
        </atom>
        <atom id="atom_Br" count="2">
            <symbol>Br</symbol>
            <name>Brom</name>
            <weight>80</weight>
            <color>#A52A2A</color>
            <textColor>#FFFFFF</textColor>
            <valence_electrons>7</valence_electrons>
        </atom>
    </atoms>
</cards>

=== elPytel/Molekuly/cards/metallurgy/molecules.xml
<?xml version="1.0" encoding="UTF-8"?>
<cards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../cards.xsd" game="Molekuly" version="1.0">
    
    <molecules>
        <molecule id="recipe_hematite" count="1">
            <title>Hematit (Železná ruda / Rez)</title>
            <formula>Fe2O3</formula>
            <smiles>O=[Fe]O[Fe]=O</smiles>
            <points>160</points>
            <image>assets/molecules/hematite.png</image>
            <lore>Oxid železitý. Nejdůležitější ruda pro výrobu surového železa. Zároveň je to hlavní chemická složka rzi, která vzniká korozí čistého kovu za přítomnosti vlhka a kyslíku.</lore>
        </molecule>

        <molecule id="recipe_magnetite" count="1">
            <title>Magnetit</title>
            <formula>Fe3O4</formula>
            <smiles>O=[Fe]O[Fe]O[Fe]=O</smiles>
            <points>232</points>
            <image>assets/molecules/magnetite.png</image>
            <lore>Oxid železnato-železitý. Nejbohatší železná ruda s přirozenými magnetickými vlastnostmi. Vzniká také na povrchu železa při kování za vysokých teplot jako okují.</lore>
        </molecule>

        <molecule id="recipe_alumina" count="1">
            <title>Oxid hlinitý</title>
            <formula>Al2O3</formula>
            <smiles>O=[Al]O[Al]=O</smiles>
            <points>102</points>
            <image>assets/molecules/alumina.png</image>
            <lore>Alumina. Meziprodukt při výrobě hliníku z bauxitu. V přírodě se vyskytuje jako minerál korund, jehož drahokamové odrůdy jsou safír a rubín.</lore>
        </molecule>

        <molecule id="recipe_coke" count="1">
            <title>Metalurgický koks</title>
            <formula>C</formula>
            <smiles>C</smiles>
            <points>12</points>
            <image>assets/molecules/coke.png</image>
            <lore>Téměř čistý uhlík získaný z černého uhlí bez přístupu vzduchu. Ve vysoké peci slouží jako palivo, ale hlavně jako redukční činidlo, které bere rudě kyslík.</lore>
        </molecule>

        <molecule id="recipe_limestone" count="1">
            <title>Vápenec (Struskotvorná přísada)</title>
            <formula>CaCO3</formula>
            <smiles>[Ca+2].[O-]C(=O)[O-]</smiles>
            <points>100</points>
            <image>assets/molecules/limestone.png</image>
            <lore>Uhličitan vápenatý. Přidává se do vysoké pece, kde se teplem rozkládá. Jeho úkolem je navázat na sebe hlušinu (písek a jíl) a vytvořit tekutou strusku.</lore>
        </molecule>

        <molecule id="recipe_lime" count="1">
            <title>Pálené vápno (Základ strusky)</title>
            <formula>CaO</formula>
            <smiles>O=[Ca]</smiles>
            <points>56</points>
            <image>assets/molecules/lime.png</image>
            <lore>Oxid vápenatý. Vzniká přímo ve vysoké peci termickým rozkladem vápence. Okamžitě reaguje s křemičitými nečistotami v rudě, čímž čistí taveninu kovu.</lore>
        </molecule>

        <molecule id="recipe_copper_ore" count="1">
            <title>Tenorit (Měděná ruda)</title>
            <formula>CuO</formula>
            <smiles>O=[Cu]</smiles>
            <points>80</points>
            <image>assets/molecules/copper_ore.png</image>
            <lore>Oxid měďnatý. Černá minerální ruda. Na rozdíl od železa je její redukce mnohem snazší a lidstvo ji dokázalo vytavit už v době kamenné, což odstartovalo dobu měděnou.</lore>
        </molecule>

        <molecule id="recipe_malachite_dust" count="1">
            <title>Malachit (Kosmetika i ruda)</title>
            <formula>CuCO3</formula>
            <smiles>[Cu+2].[O-]C(=O)[O-]</smiles>
            <points>124</points>
            <image>assets/molecules/malachite.png</image>
            <lore>Uhličitan měďnatý. Nádherný zelený minerál. V egyptské kosmetice sloužil jako oční stíny, v metalurgii jako snadno dostupný zdroj čisté mědi.</lore>
        </molecule>

        <molecule id="recipe_sodium_cyanide" count="1">
            <title>Kyanid sodný</title>
            <formula>NaCN</formula>
            <smiles>[Na+].[C-]#N</smiles>
            <points>49</points>
            <image>assets/molecules/sodium_cyanide.png</image>
            <lore>Prudce jedovatá sůl. V metalurgii je naprosto nezastupitelná, protože kyanidový aniont dokáže jako jeden z mála vytvořit stabilní rozpustný komplex s drahými kovy.</lore>
        </molecule>

        <molecule id="recipe_gold_complex" count="1">
            <title>Kyanidový komplex zlata</title>
            <formula>NaAu(CN)2</formula>
            <smiles>[Na+].[Au+].[C-]#N.[C-]#N</smiles>
            <points>272</points>
            <image>assets/molecules/gold_complex.png</image>
            <lore>Dikyanozlatan sodný. Rozpustná forma zlata, která vzniká loužením zlatonosné horniny kyanidem za přítomnosti vzdušného kyslíku (Elsnerova reakce).</lore>
        </molecule>

        <molecule id="recipe_silver_complex" count="1">
            <title>Kyanidový komplex stříbra</title>
            <formula>NaAg(CN)2</formula>
            <smiles>[Na+].[Ag+].[C-]#N.[C-]#N</smiles>
            <points>183</points>
            <image>assets/molecules/silver_complex.png</image>
            <lore>Dikyanoztříbrňan sodný. Komplexní sloučenina využívaná k získávání stříbra z rud nebo při galvanickém stříbření předmětů v klenotnictví.</lore>
        </molecule>
    </molecules>
</cards>

=== elPytel/Molekuly/cards/vitamins/molecules.xml
<?xml version="1.0" encoding="UTF-8"?>
<cards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../cards.xsd" game="Molekuly" version="1.0">
    
    <molecules>
        <molecule id="recipe_vitamin_c" count="1">
            <title>Vitamín C</title>
            <formula>C6H8O6</formula>
            <smiles>C(C1C(C(C(O1)O)O)O)=C(O)C(=O)O</smiles>
            <points>176</points>
            <image>assets/molecules/vitamin_c.png</image>
            <lore>Kyselina askorbová. Klíčový antioxidant nezbytný pro imunitu a tvorbu kolagenu. Lidé ho na rozdíl od většiny zvířat nedokážou sami syntetizovat.</lore>
        </molecule>

        <molecule id="recipe_vitamin_b3" count="2">
            <title>Vitamín B3</title>
            <formula>C6H5NO2</formula>
            <smiles>O=C(O)c1ccncc1</smiles>
            <points>123</points>
            <image>assets/molecules/vitamin_b3.png</image>
            <lore>Niacin. Podílí se na metabolismu sacharidů a tuků. Jeho nedostatek v potravě způsobuje nemoc zvanou pelagra (drsná kůže).</lore>
        </molecule>

        <molecule id="recipe_vitamin_b6" count="2">
            <title>Vitamín B6</title>
            <formula>C8H11NO3</formula>
            <smiles>Cc1ncc(CO)c(CO)c1O</smiles>
            <points>169</points>
            <image>assets/molecules/vitamin_b6.png</image>
            <lore>Pyridoxin. Hraje naprosto zásadní roli v metabolismu aminokyselin a při tvorbě červených krvinek. Podporuje správnou funkci nervového systému a imunity.</lore>
        </molecule>

        <molecule id="recipe_vitamin_b5" count="1">
            <title>Vitamín B5</title>
            <formula>C9H17NO5</formula>
            <smiles>CC(C)(CO)C(O)C(=O)NCCC(=O)O</smiles>
            <points>219</points>
            <image>assets/molecules/vitamin_b5.png</image>
            <lore>Kyselina pantothenová. Je nezbytná pro správný metabolismus všech živin v těle. Její upravená forma (panthenol) se masivně využívá v kosmetice pro regeneraci kůže a vlasů.</lore>
        </molecule>

        <molecule id="recipe_vitamin_b7" count="1">
            <title>Vitamín B7</title>
            <formula>C10H16N2O3S</formula>
            <smiles>C1C2C(C(S1)CCCCC(=O)O)NC(=O)N2</smiles>
            <points>244</points>
            <image>assets/molecules/vitamin_b7.png</image>
            <lore>Biotin neboli vitamín H. Výborně herně zapojuje atom Síry do složité organické struktury. Je klíčový pro zdraví nehtů, kůže a podporuje růst vlasů.</lore>
        </molecule>

        <molecule id="recipe_vitamin_a" count="1">
            <title>Vitamín A</title>
            <formula>C20H30O</formula>
            <smiles>CC1=C(C(CCC1)(C)C)C=CC(=CC=CC(=CCO)C)C</smiles>
            <points>286</points>
            <image>assets/molecules/vitamin_a.png</image>
            <lore>Retinol. Vitamín rozpustný v tucích. Je naprosto klíčový pro správný mechanismus vidění (tvorbu zrakového purpuru), zdraví sliznic a imunitní odpověď.</lore>
        </molecule>

        <molecule id="recipe_vitamin_b1" count="2">
            <title>Vitamín B1</title>
            <formula>C12H17ClN4OS</formula>
            <smiles>Cc1ncc(C[n+]2csc(CCO)c2C)c(N)n1.[Cl-]</smiles>
            <points>300</points>
            <image>assets/molecules/vitamin_b1.png</image>
            <lore>Thiamin. Klíčový koenzym pro přeměnu sacharidů na energii. Jeho fatální nedostatek v potravě způsobuje nervové onemocnění beri-beri.</lore>
        </molecule>

        <molecule id="recipe_vitamin_b2" count="2">
            <title>Vitamín B2</title>
            <formula>C17H20N4O6</formula>
            <smiles>Cc1cc2c(cc1C)N(C3=NC(=O)NC(=O)C3=N2)CC(C(C(CO)O)O)O</smiles>
            <points>376</points>
            <image>assets/molecules/vitamin_b2.png</image>
            <lore>Riboflavin. Důležitý pro správnou funkci buněčného dýchání, metabolismus kůže a očí. Při nedostatku vznikají bolestivé koutky úst.</lore>
        </molecule>

        <molecule id="recipe_vitamin_b9" count="1">
            <title>Vitamín B9</title>
            <formula>C19H19N7O6</formula>
            <smiles>C1=CC(=CC=C1C(=O)NC(CCC(=O)O)C(=O)O)NCC2=CN=C3C(=N2)C(=O)NC(=N3)N</smiles>
            <points>441</points>
            <image>assets/molecules/vitamin_b9.png</image>
            <lore>Kyselina listová. Naprosto esenciální pro syntézu nukleových kyselin (DNA) a pro rychlé dělení buněk. Její dostatečný příjem je kritický během těhotenství.</lore>
        </molecule>

        <molecule id="recipe_vitamin_d3" count="1">
            <title>Vitamín D3</title>
            <formula>C27H44O</formula>
            <smiles>CC(C)CCCC(C)C1CCC2C1(CCCC2=CC=C3CC(CCC3=C)O)C</smiles>
            <points>384</points>
            <image>assets/molecules/vitamin_d3.png</image>
            <lore>Cholekalciferol. Syntetizuje se v kůži působením slunečního UV záření. Řídí vstřebávání vápníku a fosforu, čímž zajišťuje tvrdost kostí a zubů.</lore>
        </molecule>

        <molecule id="recipe_vitamin_e" count="1">
            <title>Vitamín E</title>
            <formula>C29H50O2</formula>
            <smiles>CC1=C(C2=C(C(=C1C)O)CCC(O2)(C)CCCC(C)CCCC(C)CCCC(C)C)C</smiles>
            <points>430</points>
            <image>assets/molecules/vitamin_e.png</image>
            <lore>Alfa-tokoferol. Nejdůležitější antioxidant v těle rozpustný v tucích. Chrání buněčné membrány před poškozením volnými radikály a zpomaluje stárnutí buněk.</lore>
        </molecule>

        <molecule id="recipe_vitamin_k1" count="1">
            <title>Vitamín K1</title>
            <formula>C31H46O2</formula>
            <smiles>CC1=C(C(=O)c2ccccc2C1=O)CC=C(C)CCCC(C)CCCC(C)CCCC(C)C</smiles>
            <points>450</points>
            <image>assets/molecules/vitamin_k1.png</image>
            <lore>Fyllochinon. Rostlinná forma vitamínu K, který v těle bezprostředně řídí syntézu koagulačních faktorů v játrech. Je naprosto nezbytný pro srážlivost krve.</lore>
        </molecule>

        <molecule id="recipe_vitamin_b12" count="0">
            <title>Vitamín B12</title>
            <formula>C6H88CoN14O14P</formula>
            <smiles>CC1=CC2=C(C=C1C)N(C=N2)[C@@H]3[C@@H]([C@@H]([C@H](O3)CO)OP(=O)([O-])O[C@H](C)CNC(=O)CC[C@@]4([C@H]([C@@H]5[C@]6([C@@]([C@@H](C(=N6)/C(=C\7/[C@@]([C@@H](C(=N7)/C=C\8/C([C@@H](C(=N8)/C(=C4\[N-]5)/C)CCC(=O)N)(C)C)CCC(=O)N)(C)CC(=O)N)/C)CCC(=O)N)(C)CC(=O)N)C)CC(=O)N)C)O.[C-]#N.[Co+3]</smiles>
            <points>1354</points>
            <image>assets/molecules/vitamin_b12.png</image>
            <lore>Kyanokobalamin. Gigantická a nejsložitější struktura mezi vitamíny. Obsahuje vzácný iont kobaltu. Je kritický pro tvorbu krve a správnou funkci nervové soustavy.</lore>
        </molecule>
    </molecules>
</cards>

=== elPytel/Molekuly/cards/cosmetics/molecules.xml
<?xml version="1.0" encoding="UTF-8"?>
<cards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../cards.xsd" game="Molekuly" version="1.0">

    <molecules>
        <molecule id="recipe_urea" count="1">
            <title>Močovina</title>
            <formula>CH4N2O</formula>
            <smiles>NC(=O)N</smiles>
            <points>60</points>
            <image>assets/molecules/urea.png</image>
            <lore>Urea. Vysoce účinné dusíkaté hnojivo, které má zároveň nezastupitelnou roli v hydratačních krémech.</lore>
        </molecule>

        <molecule id="recipe_salicylic_acid" count="1">
            <title>Kyselina salicylová</title>
            <formula>C7H6O3</formula>
            <smiles>OC1=CC=CC=C1C(=O)O</smiles>
            <points>138</points>
            <image>assets/molecules/salicylic_acid.png</image>
            <lore>Beta-hydroxykyselina (BHA) masivně využívaná v kosmetice k čištění pleti a uvolňování ucpaných pórů. Přirozeně se vyskytuje v kůře vrby bílé.</lore>
        </molecule>

        <molecule id="recipe_lactic_acid" count="1">
            <title>Kyselina mléčná</title>
            <formula>C3H6O3</formula>
            <smiles>CC(C(=O)O)O</smiles>
            <points>90</points>
            <image>assets/molecules/lactic_acid.png</image>
            <lore>V kosmetice se využívá pro hydrataci a omlazení pleti (AHA kyselina). Přirozeně vzniká při mléčném kvašení jogurtů nebo v lidských svalech při extrémní zátěži.</lore>
        </molecule>

       <molecule id="recipe_sodium_fluoride" count="1">
            <title>Fluorid sodný</title>
            <formula>NaF</formula>
            <smiles>[Na+].[F-]</smiles>
            <points>42</points>
            <image>assets/molecules/sodium_fluoride.png</image>
            <lore>Klíčová složka zubních past. Fluoridové ionty reagují se zubní sklovinou a přeměňují ji na odolnější hydroxyapatit, čímž aktivně chrání zuby před kyselinami a vznikem kazu.</lore>
        </molecule>

        <molecule id="recipe_silica" count="1">
            <title>Silica (Oxid křemičitý)</title>
            <formula>SiO2</formula>
            <smiles>O=[Si]=O</smiles>
            <points>60</points>
            <image>assets/molecules/silica.png</image>
            <lore>V zubních pastách funguje jako jemné mechanické abrazivum, které odstraňuje zubní plak. V dekorativní kosmetice (pudrech) zase absorbuje přebytečný kožní maz a matuje pleť.</lore>
        </molecule>

        <molecule id="recipe_hydrated_silica" count="1">
            <title>Hydratovaná silica</title>
            <formula>H2SiO3</formula>
            <smiles>O=[Si](O)O</smiles>
            <points>78</points>
            <image>assets/molecules/hydrated_silica.png</image>
            <lore>Kyselina křemičitá. Má prokazatelně měkčí a šetrnější částice než čistý křemenný prášek. Čistí povrch zubů mechanicky, ale bez rizika poškrábání citlivé skloviny.</lore>
        </molecule>

        <molecule id="recipe_novamin" count="1">
            <title>Fosfokřemičitan sodno-vápenatý</title>
            <formula>CaNaO6PSi</formula>
            <smiles>[Na+].[Ca+2].[O-]P(=O)([O-])[O-].O=[Si]=O</smiles>
            <points>218</points>
            <image>assets/molecules/novamin.png</image>
            <lore>Bioaktivní sklo (známé jako NovaMin). V kontaktu se slinami okamžitě uvolňuje ionty vápníku a fosforu, které přirozeně krystalizují přímo na zubech a opravují poškozená místa.</lore>
        </molecule>

        <molecule id="recipe_citric_acid" count="1">
            <title>Kyselina citronová</title>
            <formula>C6H8O7</formula>
            <smiles>OC(=O)CC(O)(CC(=O)O)C(=O)O</smiles>
            <points>192</points>
            <image>assets/molecules/citric_acid.png</image>
            <lore>Přírodní alfa-hydroxykyselina (AHA). V kosmetice se používá k úpravě pH produktů, aby nedráždily pokožku. V šampónech pomáhá vyhlazovat vlasové kutikuly, které pak lépe odrážejí světlo.</lore>
        </molecule>

        <molecule id="recipe_propylene_glycol" count="1">
            <title>Propylenglykol</title>
            <formula>C3H8O2</formula>
            <smiles>CC(O)CO</smiles>
            <points>76</points>
            <image>assets/molecules/propylene_glycol.png</image>
            <lore>Intenzivní zvlhčovadlo (humektant). Navazuje na sebe vlhkost z okolí a uzamyká ji v kůži. Zároveň pomáhá ostatním aktivním látkám pronikat hlouběji do epidermis.</lore>
        </molecule>

        <molecule id="recipe_hexylene_glycol" count="1">
            <title>Hexylenglykol</title>
            <formula>C6H14O2</formula>
            <smiles>CC(O)CC(C)(C)O</smiles>
            <points>118</points>
            <image>assets/molecules/hexylene_glycol.png</image>
            <lore>Multifunkční organické rozpouštědlo. Snižuje viskozitu kosmetických přípravků, díky čemuž jsou husté krémy a emulze tekutější, hladší a podstatně lépe se roztírají.</lore>
        </molecule>

        <molecule id="recipe_panthenol" count="1">
            <title>Panthenol</title>
            <formula>C9H19NO4</formula>
            <smiles>CC(C)(CO)C(O)C(=O)NCCCO</smiles>
            <points>205</points>
            <image>assets/molecules/panthenol.png</image>
            <lore>Provitamín B5. Má hluboké zklidňující vlastnosti, stimuluje obnovu buněk a udržuje hydrataci. Naprostý základ všech hojivých mastí a regeneračních krémů po opalování.</lore>
        </molecule>

        <molecule id="recipe_limonene" count="1">
            <title>Limonen</title>
            <formula>C10H16</formula>
            <smiles>CC1=CCC(CC1)C(=C)C</smiles>
            <points>136</points>
            <image>assets/molecules/limonene.png</image>
            <lore>Citrusový terpen obsažený v kůře pomerančů. Dodává kosmetice svěží ovocnou vůni. Má silné demaskovací schopnosti a dokáže účinně odmašťovat povrchy.</lore>
        </molecule>

        <molecule id="recipe_linalool" count="1">
            <title>Linalool</title>
            <formula>C10H18O</formula>
            <smiles>CC(=CCCC(C)(C=C)O)C</smiles>
            <points>154</points>
            <image>assets/molecules/linalool.png</image>
            <lore>Vonný terpenový alkohol, který najdeme v levanduli nebo jasmínu. Dodává krémům a parfémům příjemné květinové tóny, v legislativě však patří mezi hlídané potenciální alergeny.</lore>
        </molecule>

        <molecule id="recipe_carbomer_monomer" count="1">
            <title>Karbomer (Základ gelů)</title>
            <formula>C3H4O2</formula>
            <smiles>C=CC(=O)O</smiles>
            <points>72</points>
            <image>assets/molecules/carbomer_monomer.png</image>
            <lore>Kyselina akrylová (monomer karbomeru). Tento syntetický polymer dokáže ve vodě absorbovat až tisícinásobek své váhy. Používá se jako zahušťovadlo pro čiré pleťové gely a dezinfekce.</lore>
        </molecule>

        <molecule id="recipe_sodium_bromide" count="1">
            <title>Bromid sodný</title>
            <formula>NaBr</formula>
            <smiles>[Na+].[Br-]</smiles>
            <points>103</points>
            <image>assets/molecules/sodium_bromide.png</image>
            <lore>Anorganická sůl. V šampónech a tekutých mýdlech se používá k přesné regulaci hustoty a viskozity. V historii sloužil také jako bezpečný mírný konzervační prostředek.</lore>
        </molecule>

    </molecules>
</cards>

=== elPytel/Molekuly/cards/base_game/atoms.xml
<?xml version="1.0" encoding="UTF-8"?>
<cards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../cards.xsd" game="Molekuly" version="1.0">
    
    <atoms>
        <atom id="atom_H" count="2">
            <symbol>H</symbol>
            <name>Vodik</name>
            <weight>1</weight>
            <color>#FFFFFF</color>
            <textColor>#000000</textColor>
            <valence_electrons>1</valence_electrons>
        </atom>
        <atom id="atom_C" count="2">
            <symbol>C</symbol>
            <name>Uhlik</name>
            <weight>12</weight>
            <color>#333333</color>
            <textColor>#FFFFFF</textColor>
            <valence_electrons>4</valence_electrons>
        </atom>
        <atom id="atom_O" count="6">
            <symbol>O</symbol>
            <name>Kyslik</name>
            <weight>16</weight>
            <color>#FF4D4D</color>
            <textColor>#FFFFFF</textColor>
            <valence_electrons>6</valence_electrons>
        </atom>
        <atom id="atom_N" count="6">
            <symbol>N</symbol>
            <name>Dusik</name>
            <weight>14</weight>
            <color>#3366FF</color>
            <textColor>#FFFFFF</textColor>
            <valence_electrons>5</valence_electrons>
        </atom>
        <atom id="atom_Na" count="6">
            <symbol>Na</symbol>
            <name>Sodik</name>
            <weight>23</weight>
            <color>#9933FF</color>
            <textColor>#FFFFFF</textColor>
            <valence_electrons>1</valence_electrons>
        </atom>
        <atom id="atom_Cl" count="6">
            <symbol>Cl</symbol>
            <name>Chlor</name>
            <weight>35</weight>
            <color>#00CC44</color>
            <textColor>#FFFFFF</textColor>
            <valence_electrons>7</valence_electrons>
        </atom>
        <atom id="atom_S" count="4">
            <symbol>S</symbol>
            <name>Sira</name>
            <weight>32</weight>
            <color>#FFCC00</color>
            <textColor>#000000</textColor>
            <valence_electrons>6</valence_electrons>
        </atom>
        <atom id="atom_P" count="4">
            <symbol>P</symbol>
            <name>Fosfor</name>
            <weight>31</weight>
            <color>#FF9900</color>
            <textColor>#000000</textColor>
            <valence_electrons>5</valence_electrons>
        </atom>
        <atom id="atom_K" count="4">
            <symbol>K</symbol>
            <name>Draslik</name>
            <weight>39</weight>
            <color>#B380FF</color>
            <textColor>#FFFFFF</textColor>
            <valence_electrons>1</valence_electrons>
        </atom>
    </atoms>
</cards>

=== elPytel/Molekuly/cards/vitamins/atoms.xml
<?xml version="1.0" encoding="UTF-8"?>
<cards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../cards.xsd" game="Molekuly" version="1.0">
    
    <atoms>
        <atom id="atom_Co" count="0">
            <symbol>Co</symbol>
            <name>Kobalt</name>
            <weight>59</weight>
            <color>#4682B4</color>
            <textColor>#FFFFFF</textColor>
            <valence_electrons>3</valence_electrons>
        </atom>
    </atoms>
</cards>
